SConscript(['main/SConscript'])
env = Environment(CC = '8cc', LIBS=['msvcrt'], CPPPATH='.', CCFLAGS='/y',
	LINKFLAGS='/LARGEADDRESSAWARE:NO /DEBUG /MACHINE:X64 /OPT:REF /INCREMENTAL:NO /SUBSYSTEM:CONSOLE /ENTRY:main')

printTestProgram = env.Program(['print.c', 'main/testmain.obj']),
printTest = env.Command('print.test', printTestProgram, "$SOURCE > $TARGET 2>&1")	

testSources = [
	#'align',
	#'arith',
	'assign',
	'bitop',
	'builtin',
	#'cast',
	#'comp',
	#'control',
	#'conversion',
	#'decl',
	'enum',
	'extern',
	#'float',
	#'funcargs',
	#'function',
	#'generic',
	#'global',
	'import',
	#'initializer',
	#'int',
	#'lex',
	#'literal',
	#'macro',
	#'noreturn',
	#'number',
	#'oldstyle',
	#'pointer',
	#'scope',
	#'sizeof',
	'staticassert',
	#'stmtexpr',
	#'struct',
	#'type',
	#'typeof',
	'union',
	'usualconv',
	#'varargs',
]

for testSource in testSources:
	testProgram = env.Program([testSource + '.c', 'main/testmain.obj']),
	test = env.Command(testSource + '.test', testProgram, "$SOURCE > $TARGET 2>&1")
	Depends(testProgram, printTest)
